<h1>Numpy</h1>
<h6>!! 넘파이는 전체가 같은 자료형의 데이터만 저장되어야한다.</h6>
<h6>   - 숫자와 문자형을 같이 넣으면 숫자를 문자형으로 변경한다.</h6>
<h6>!! 인덱싱과 슬라이싱</h6>
<h6>!! 생성함수</h6>

In [6]:
a = [[10, 20], 20, 30]

In [3]:
import numpy as np

In [7]:
type(a)

list

In [10]:
l1 = [1, 2, 3, 4 , 5]
l2 = np.array(l1)

In [11]:
type(l1), type(l2)

(list, numpy.ndarray)

In [12]:
l2

array([1, 2, 3, 4, 5])

In [18]:
l3 = np.array(l1, dtype= 'float32')

In [19]:
print( type(l1), type(l2))
print( type(l1[0]), type(l2[0]), type(l3[0]))

<class 'list'> <class 'numpy.ndarray'>
<class 'int'> <class 'numpy.int64'> <class 'numpy.float32'>


In [20]:
a = np.array([[1,2,3],[4,5,6]])
print (a.shape)

(2, 3)


In [21]:
print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
a.shape = (3,2)
print(a.shape)
print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [34]:
a = np.arange(24)
print(a.ndim,'\n')
print(a, '\n')

b = a.reshape(2,4,3)
print(b.ndim,'\n')
print(b,'\n')

1 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

3 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] 



In [42]:
x = np.empty([3,2], dtype=float)
print(x, '\n')
x = np.zeros((5,), dtype="int")
print(x, '\n')
x = np.ones([2,2], dtype=int)
print(x, '\n')

[[ 2.25078153e+184  6.38332814e-321]
 [ 0.00000000e+000  1.23976761e-311]
 [ 0.00000000e+000 -1.57234264e-063]] 

[0 0 0 0 0] 

[[1 1]
 [1 1]] 



In [43]:
x = np.arange(5, dtype = float) 
print (x)

[0. 1. 2. 3. 4.]


In [44]:
x = np.arange(10,20,2) # from, to, step
print (x)

[10 12 14 16 18]


In [47]:
a = np.linspace(1.0, 2.0, num = 5)
print (a, '\n')
x = np.linspace(10,20, 5, endpoint = False)
print (x, '\n')
x = np.linspace(1,2,5, retstep = True)
print (x, '\n')

[1.   1.25 1.5  1.75 2.  ] 

[10. 12. 14. 16. 18.] 

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25)) 



In [49]:
a = np.arange(10)
b = a[2:7:2] # from, to, step
print (b, '\n')
a = np.arange(10)
b = a[5]
print (b)

[2 4 6] 

5


In [50]:
a = np.arange(10)
print (a[2:])

[2 3 4 5 6 7 8 9]


In [53]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a, '\n')
print (a.shape, '\n')
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]] 

(3, 3) 

[[3 4 5]
 [4 5 6]]


In [63]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
y = x[[0,1,2], [0,1,0]]
print (y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [59]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print(x, '\n')
z = x[1:4,1:3]
print (z, '\n')
y = x[1:4,[1,2]]
print (y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 4  5]
 [ 7  8]
 [10 11]] 

[[ 4  5]
 [ 7  8]
 [10 11]]


In [61]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(np.isnan(a))
print(~np.isnan(a))
print(a[~np.isnan(a)])

[ True False False  True False False False]
[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]


In [65]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


In [72]:
for i in a-1:
    print(a[i] * b)

[10 20 30 40]
[20 40 60 80]
[ 30  60  90 120]
[ 40  80 120 160]


In [74]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
print (a * b)

[[ 0.  0.  0.]
 [10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]


In [76]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
for x in np.nditer(a, order = 'C'):
    print (x, end=' ')
print ('\n')
for x in np.nditer(a, order = 'F'):
    print (x, end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

0 20 40 5 25 45 10 30 50 15 35 55 

In [80]:
import pandas as pd

In [81]:
data = pd.read_csv('source/weather_data.csv', header=0, sep = ",")

In [89]:
print(data[:3])


   지점번호 지점명          일시  평균기온(℃)  최고기온(℃) 최고기온시각  최저기온(℃) 최저기온시각   일교차
0   108  서울  1907-10-01     13.5     20.7    NaN      7.9    NaN  12.8
1   108  서울  1907-10-02     16.2     22.0    NaN      7.9    NaN  14.1
2   108  서울  1907-10-03     16.2     21.3    NaN     13.1    NaN   8.2


In [147]:
day_list = data[['지점명', '일시']]
weather_info = data[['지점번호', '평균기온(℃)', '최고기온(℃)', '최고기온시각', '최저기온(℃)', '최저기온시각','일교차']]
new_weather_info = data[['평균기온(℃)', '최고기온(℃)', '최저기온(℃)']]

In [148]:
print(new_weather_info[:5])

   평균기온(℃)  최고기온(℃)  최저기온(℃)
0     13.5     20.7      7.9
1     16.2     22.0      7.9
2     16.2     21.3     13.1
3     16.5     22.0     11.2
4     17.6     25.4     10.9


In [149]:
nn_new_weather_info = new_weather_info.dropna()

In [91]:
type(day_list)

pandas.core.frame.DataFrame

In [92]:
print(day_list[:5])

  지점명          일시
0  서울  1907-10-01
1  서울  1907-10-02
2  서울  1907-10-03
3  서울  1907-10-04
4  서울  1907-10-05


In [94]:
print(weather_info[:5])

   지점번호  평균기온(℃)  최고기온(℃) 최고기온시각  최저기온(℃) 최저기온시각   일교차
0   108     13.5     20.7    NaN      7.9    NaN  12.8
1   108     16.2     22.0    NaN      7.9    NaN  14.1
2   108     16.2     21.3    NaN     13.1    NaN   8.2
3   108     16.5     22.0    NaN     11.2    NaN  10.8
4   108     17.6     25.4    NaN     10.9    NaN  14.5


In [165]:
# 원하는 열의 인덱스 리스트 (예: 지점번호, 일시, 평균기온)
# 0: 지점번호, 2: 일시, 3: 평균기온
selected_columns_indices = [1, 2, 4]

# 원하는 열만 선택하여 새로운 배열 생성
new_weather = na_weather_info[:, selected_columns_indices]

In [166]:
na_day_list = day_list.to_numpy()
na_weather_info = weather_info.to_numpy()
na_nn_new_weather_info = nn_new_weather_info.to_numpy()

In [101]:
print(type(na_day_list), '\n')
print(type(na_weather_info), '\n')
print(na_day_list[:5], '\n')
print(na_weather_info[:5])


<class 'numpy.ndarray'> 

<class 'numpy.ndarray'> 

[['서울' '1907-10-01']
 ['서울' '1907-10-02']
 ['서울' '1907-10-03']
 ['서울' '1907-10-04']
 ['서울' '1907-10-05']] 

[[108 13.5 20.7 nan 7.9 nan 12.8]
 [108 16.2 22.0 nan 7.9 nan 14.1]
 [108 16.2 21.3 nan 13.1 nan 8.2]
 [108 16.5 22.0 nan 11.2 nan 10.8]
 [108 17.6 25.4 nan 10.9 nan 14.5]]


In [102]:
print(na_weather_info.shape)

(42016, 7)


In [111]:
print(max(na_weather_info[:,2]), np.argmax(na_weather_info[:,2]))
print(max(na_weather_info[:,6]), np.argmax(na_weather_info[:,6]))

39.6 40051
21.8 12619


In [123]:
a1 = np.argmax(na_weather_info[:,2])
a2 = np.argmax(na_weather_info[:,6])
print(a1, a2)

40051 12619


In [124]:
print(max(na_weather_info[:,2]), np.argmax(na_weather_info[:,2]), na_day_list[40051,:])
print(max(na_weather_info[:,6]), np.argmax(na_weather_info[:,6]), na_day_list[12619,:])
print(max(na_weather_info[:,2]), np.argmax(na_weather_info[:,2]), na_day_list[a1,:])
print(max(na_weather_info[:,6]), np.argmax(na_weather_info[:,6]), na_day_list[a2,:])

39.6 40051 ['서울' '2018-08-01']
21.8 12619 ['서울' '1942-04-19']
39.6 40051 ['서울' '2018-08-01']
21.8 12619 ['서울' '1942-04-19']


In [119]:
print(na_weather_info[:,2])
print(na_weather_info[:,6])

print(np.mean(na_weather_info[:,2]))
print(np.mean(na_weather_info[:,6]))

[20.7 22.0 21.3 ... 6.2 3.8 -6.4]
[12.8 14.1 8.2 ... 2.5 13.7 6.0]
nan
nan


In [130]:
print(new_weather[:])

[[13.5 20.7 7.9]
 [16.2 22.0 7.9]
 [16.2 21.3 13.1]
 ...
 [4.9 6.2 3.7]
 [-4.1 3.8 -9.9]
 [-9.8 -6.4 -12.4]]


In [167]:
print(new_weather.dtype)  # 배열의 데이터 타입 출력

object


In [168]:
nn_new_weather = np.where(new_weather == 'nan', np.nan, new_weather).astype(float)

In [169]:
nn2_new_weather = nn_new_weather[:,:].astype(float)

In [170]:
nn3_new_weather = nn2_new_weather[~np.isnan(nn2_new_weather)]

In [171]:
print(nn3_new_weather.shape, type(nn3_new_weather))

(123774,) <class 'numpy.ndarray'>


In [172]:
t = na_nn_new_weather_info

# 넘파이에서 nan 제거
t2 = nn3_new_weather

In [179]:
print(t2.shape, type(t2))
print(t2[:,1])

(123774,) <class 'numpy.ndarray'>


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [173]:
# 넘파이에서 nan 제거
print('평균기온의 평균 : ', np.mean(t2[:,0]))
print('평균기온의 최저 : ', np.min(t2[:,0]))
print('최고기온의 평균 : ', np.mean(t2[:,1]))

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [164]:
print('평균기온의 평균 : ', np.mean(t[:,0]))
print('평균기온의 최저 : ', np.min(t[:,0]))
print('최고기온의 평균 : ', np.mean(t[:,1]))

평균기온의 평균 :  11.798705642815591
평균기온의 최저 :  -19.2
최고기온의 평균 :  16.799835175489623


In [185]:
print(np.min(t[0]), np.min(t[1]), np.min(t[2]))

7.9 7.9 13.1
