In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
import import_ipynb
import model

In [7]:
df = load_wine()

In [12]:
x = df['data']
y = df['target']
y2 = np.where(y == 0, 1, -1)

In [13]:
y2

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1])

In [11]:
values, counts = np.unique(y, return_counts= True)
for value, count in zip(values, counts):
    print(f"Class {value}: {count}")

Class -1: 119
Class 1: 59


In [15]:
rw, re = model.fit(x, y2, eta = 0.1, n_iter = 30)

In [16]:
rw, re

(array([  -4.8   ,  -48.016 ,   -0.762 ,   -4.51  ,  -47.68  , -251.2   ,
          -4.73  ,    9.722 ,   -2.972 ,    9.042 ,    6.488 ,   -5.9912,
           4.554 ,  -32.    ]),
 array([3., 3., 3., 3., 2., 3., 3., 3., 3., 2., 3., 3., 3., 3., 2., 3., 3.,
        3., 3., 2., 3., 3., 3., 3., 2., 3., 3., 3., 3., 2.]))

In [18]:
error_cnt = 0
for xv, t in zip(x,y2):
    pv = model.predict(xv, rw)
    error_cnt += (pv != t)
print("Accuracy : {0}".format(error_cnt / len(y2)))

Accuracy : 0.33146067415730335


In [35]:
x.shape

(178, 13)

In [19]:
x.max(axis=0)

array([1.483e+01, 5.800e+00, 3.230e+00, 3.000e+01, 1.620e+02, 3.880e+00,
       5.080e+00, 6.600e-01, 3.580e+00, 1.300e+01, 1.710e+00, 4.000e+00,
       1.680e+03])

In [20]:
x.max(axis=1)

array([1065., 1050., 1185., 1480.,  735., 1450., 1290., 1295., 1045.,
       1045., 1510., 1280., 1320., 1150., 1547., 1310., 1280., 1130.,
       1680.,  845.,  780.,  770., 1035., 1015.,  845.,  830., 1195.,
       1285.,  915., 1035., 1285., 1515.,  990., 1235., 1095.,  920.,
        880., 1105., 1020.,  760.,  795., 1035., 1095.,  680.,  885.,
       1080., 1065.,  985., 1060., 1260., 1150., 1265., 1190., 1375.,
       1060., 1120.,  970., 1270., 1285.,  520.,  680.,  450.,  630.,
        420.,  355.,  678.,  502.,  510.,  750.,  718.,  870.,  410.,
        472.,  985.,  886.,  428.,  392.,  500.,  750.,  463.,  278.,
        714.,  630.,  515.,  520.,  450.,  495.,  562.,  680.,  625.,
        480.,  450.,  495.,  290.,  345.,  937.,  625.,  428.,  660.,
        406.,  710.,  562.,  438.,  415.,  672.,  315.,  510.,  488.,
        312.,  680.,  562.,  325.,  607.,  434.,  385.,  407.,  495.,
        345.,  372.,  564.,  625.,  465.,  365.,  380.,  380.,  378.,
        352.,  466.,

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
x2 = MinMaxScaler().fit_transform(x)

In [30]:
rw, re = model.fit(x2, y2, eta = 0.1, n_iter = 100)

In [33]:
error_cnt = 0
for xv, t in zip(x2,y2):
    pv = model.predict(xv, rw)
    error_cnt += (pv != t)
print("Accuracy : {0}".format(1- error_cnt / len(y2)))

Accuracy : 1.0
