<h1>fit_transform & one_hot_incoding & train_test_split
</h1>

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder # 범주형 -> 순위형 변경 도구

In [73]:
df2 = pd.DataFrame([
    ['green', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1'],
])
df2.columns = ['color', 'size', 'price', 'classlabel']
df2

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [74]:
#np.unique(df2['classlabel'], return_counts= True)
class_mapping = { 'class1' : 0, 'class2' : 1, 'class3' : 2}
class_mapping = {
    label : idx for idx, label in enumerate(np.unique(df2['classlabel']))
}
df2['classlabel2'] = df2['classlabel'].map(class_mapping)
df2

color size  price classlabel  classlabel2
0  green    M   10.1     class1            0
1    red    L   13.5     class2            1
2   blue   XL   15.3     class1            0

In [75]:
inv_class_mapping = { v : k for k, v in class_mapping.items() }
print(inv_class_mapping)
df2['classlabel2'] = df2['classlabel2'].map(inv_class_mapping)
df2

{0: 'class1', 1: 'class2'}


color size  price classlabel classlabel2
0  green    M   10.1     class1      class1
1    red    L   13.5     class2      class2
2   blue   XL   15.3     class1      class1

In [76]:
df2

color size  price classlabel classlabel2
0  green    M   10.1     class1      class1
1    red    L   13.5     class2      class2
2   blue   XL   15.3     class1      class1

In [77]:
cl = LabelEncoder()
print(df2['classlabel'].values)
#y = cl.fit_transform(df2['classlabel'].values) #fit_transform은 아래처럼 나누어서 사용도 가능
cl.fit(df2['classlabel'].values)
y = cl.transform(df2['classlabel'].values)
y

['class1' 'class2' 'class1']


array([0, 1, 0])

In [78]:
df2

color size  price classlabel classlabel2
0  green    M   10.1     class1      class1
1    red    L   13.5     class2      class2
2   blue   XL   15.3     class1      class1

In [79]:
df2['classlabel'] = cl.fit_transform(df2['classlabel'].values)
df2

color size  price  classlabel classlabel2
0  green    M   10.1           0      class1
1    red    L   13.5           1      class2
2   blue   XL   15.3           0      class1

In [80]:
df2['classlabel3'] = cl.inverse_transform(df2['classlabel'].values)
df2

color size  price  classlabel classlabel2 classlabel3
0  green    M   10.1           0      class1      class1
1    red    L   13.5           1      class2      class2
2   blue   XL   15.3           0      class1      class1

In [81]:
df2.drop(['classlabel3'], axis= 1)

color size  price  classlabel classlabel2
0  green    M   10.1           0      class1
1    red    L   13.5           1      class2
2   blue   XL   15.3           0      class1

In [82]:
df2

color size  price  classlabel classlabel2 classlabel3
0  green    M   10.1           0      class1      class1
1    red    L   13.5           1      class2      class2
2   blue   XL   15.3           0      class1      class1

<h1>one-hot-encoding</h1>

In [83]:
from sklearn.preprocessing import OneHotEncoder


In [ ]:
x = df2[['color', 'price']].values
print(x)


[['green' 10.1]
 ['red' 13.5]
 ['blue' 15.3]]


In [86]:
ohe = OneHotEncoder()
encoded = ohe.fit_transform(x[:, [0]]).toarray()

In [87]:
encoded

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [88]:
pd.get_dummies(df2[['color', 'price']])

price  color_blue  color_green  color_red
0   10.1       False         True      False
1   13.5       False        False       True
2   15.3        True        False      False

In [95]:
df = pd.read_csv('winequality-white.csv', sep= ';')

In [96]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [99]:
df['quality'].unique()

array([6, 5, 7, 8, 4, 3, 9])

In [101]:
#데이터 분할
from sklearn.model_selection import train_test_split

In [117]:

X, y = df.iloc[:, :-1].values, df.iloc[:, -1].values
X_train, X_test, y_train, y_test = \
train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3428, 11), (1470, 11), (3428,), (1470,))

In [118]:
np.unique(y, return_counts = True)

(array([3, 4, 5, 6, 7, 8, 9]),
 array([  20,  163, 1457, 2198,  880,  175,    5]))

In [ ]:
np.unique(y_train, return_counts = True) # 문제점: 교육자료에서 9등급 와인 모두를 가져감

(array([3, 4, 5, 6, 7, 8, 9]),
 array([  13,  123, 1031, 1530,  600,  126,    5]))

In [120]:
np.unique(y_test, return_counts = True)

(array([3, 4, 5, 6, 7, 8]), array([  7,  40, 426, 668, 280,  49]))

In [ ]:
X, y = df.iloc[:, :-1].values, df.iloc[:, -1].values
X_train, X_test, y_train, y_test = \
train_test_split(X, y, test_size=0.3, random_state=42, stratify= y) # stratify에 tarhet 변수 주기
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3428, 11), (1470, 11), (3428,), (1470,))

In [122]:
np.unique(y_train, return_counts = True) # 문제점: 교육자료에서 9등급 와인 모두를 가져감

(array([3, 4, 5, 6, 7, 8, 9]),
 array([  14,  114, 1020, 1538,  616,  122,    4]))

In [123]:
np.unique(y_test, return_counts = True)

(array([3, 4, 5, 6, 7, 8, 9]), array([  6,  49, 437, 660, 264,  53,   1]))