In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [88]:
df = load_iris()

In [89]:
print(type(df)) # dict와 유사한 구조
print(df.keys())
#print(df['DESCR'])
#print(df['data']) # feature, 입력데이터 (x)
#print(np.unique(df['target'])) target data (y)
print(df['target_names'])



<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
['setosa' 'versicolor' 'virginica']


In [90]:
def NI(x, w): # x, w  1D array 형식
    return np.dot(x, w[1:]) + w[0]

In [91]:
def activation(v):
    if v <= 0:
        return -1
    
    else:
        return 1

In [92]:
def activation(v):
    return 1 if v > 0 else -1 

In [93]:
NI([1, 2, 3, 4, 5], [10, 20, 30, 40 ,50 ,60])

np.int64(710)

In [94]:
activation(0.7), activation(-0.2)

(1, -1)

In [95]:
def predict(x, w):
    net_value = NI(x, w)
    activatied_value = activation(net_value)
    return activatied_value

In [96]:
predict([1, 2, 3, 4, 5], [10, 20, 30, 40 ,50 ,60])

1

In [ ]:
def fit(x, y, eta, n_iter):    
    """
    데이터를 사용해서 perceptron 모델을 훈련하는 함수\n\n
    [전달인자]
    1. X : feature
    2. y : target
    3. eta : 학습률
    4. n_iter : 학습 반복 횟수
    """
    w = np.zeros(x.shape[1] + 1) # X.shape : 2차원 배열의 열 갯수
    errors = np.zeros(n_iter) # 학습 반복 횟수 크기의 오차 배열 만들기 (오차 로그용)

    for idx in np.arange(n_iter): # 학습 반복
        sum_of_error = 0
        for xv, t in zip(x, y): # 한 행의 입력 + 타겟을 뽑아서 학습 실행 * 행 갯수
            output = predict(xv, w) # net_input + activation -> 1 or -1 반환
            error = t - output      # 오차 계산 (실제값 - 출력값)
            # sum_of_error += error   # 현재 학습 반복의 에러를 합산
            sum_of_error += 1 if error != 0 else 0 # 현재 학습 반복의 에러를 합산
            delta = eta * error     # 가중치 업데이트에 적용할 값 계산
            w[1:] += delta * xv     # 가중치 업데이트
            w[0] += delta * 1       # 가중치(편향) 업데이트

        errors[idx] = sum_of_error  # 에러 로그에 현재 학습 반복의 에러 추가

    return w, errors



In [98]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [99]:
df['data'][:50, 0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. ])

In [100]:
"""
plt.scatter(df['data'][:50, 0],
            df['data'][:50, 1],
            label = 's')

plt.scatter(df['data'][50:100, 0],
            df['data'][50:100, 1],
            label = 'b')

plt.scatter(df['data'][100:150, 0],
            df['data'][100:150, 1],
            label = 'c')

plt.legend()
plt.show()
"""

"\nplt.scatter(df['data'][:50, 0],\n            df['data'][:50, 1],\n            label = 's')\n\nplt.scatter(df['data'][50:100, 0],\n            df['data'][50:100, 1],\n            label = 'b')\n\nplt.scatter(df['data'][100:150, 0],\n            df['data'][100:150, 1],\n            label = 'c')\n\nplt.legend()\nplt.show()\n"

In [101]:
x = df['data'][:100]
y = df['target'][:100]
#y = list(map(lambda v : -1 if v == 0 else 1, y))
y = np.where(y == 0, -1, 1) # y의 각 값이 0이면 -1, 아니면 1로 변경 ( 모델과 출력 값이 같도록 수정)
eta, n_iter = 0.1, 10

result_w, result_errors = fit(x, y, eta, n_iter)

In [102]:
result_w, result_errors

(array([-0.2 , -0.22, -0.72,  1.04,  0.44]),
 array([1., 3., 1., 0., 0., 0., 0., 0., 0., 0.]))

In [103]:
sum_of_error = 0
for vx, t in zip(x, y):
    predicted_value = predict(vx, result_w)
    
    sum_of_error += (predicted_value != t)
print("Accuracy: {0}".format(1 - sum_of_error / 100))

Accuracy: 1.0
